// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Clear Chat', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Clear Chat', async function() {
    await driver.get("http://localhost:3000/chat")
    await driver.manage().window().setRect({ width: 1935, height: 1095 })
    await driver.findElement(By.css(".MuiListItem-root:nth-child(2) > .MuiListItemText-root > .MuiTypography-root:nth-child(1)")).click()
    await driver.findElement(By.css(".MuiListItem-root:nth-child(3) .MuiTypography-root .MuiTypography-root:nth-child(1)")).click()
    await driver.findElement(By.css(".MuiListItem-root:nth-child(1) .MuiTypography-root .MuiTypography-root:nth-child(1)")).click()
    await driver.findElement(By.css(".border-b-2")).click()
    await driver.findElement(By.css(".css-1uxm02a-MuiButtonBase-root-MuiButton-root:nth-child(1)")).click()
  })
})
