// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Create group', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Create group', async function() {
    await driver.get("http://localhost:3000/chat")
    await driver.manage().window().setRect({ width: 1935, height: 1095 })
    {
      const element = await driver.findElement(By.css(".rounded-lg > path"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".rounded-lg > path")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".MuiButtonBase-root:nth-child(2)")).click()
    await driver.findElement(By.id("_r_d_")).click()
    await driver.findElement(By.id("_r_d_")).sendKeys("Testing-1")
    await driver.findElement(By.id("_r_f_")).click()
    await driver.findElement(By.id("_r_f_")).sendKeys("bs aise he bana diya")
    await driver.findElement(By.css(".css-z2qibm-MuiListItem-root:nth-child(1) .MuiTypography-body2")).click()
    await driver.findElement(By.css(".css-z2qibm-MuiListItem-root:nth-child(2) .MuiTypography-body1")).click()
    await driver.findElement(By.css(".MuiButton-fullWidth")).click()
  })
})
