// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Kick Out User', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Kick Out User', async function() {
    await driver.get("http://localhost:3000/chat")
    await driver.manage().window().setRect({ width: 872, height: 693 })
    await driver.findElement(By.css(".h-4 > path")).click()
    await driver.findElement(By.css(".MuiContainer-root:nth-child(1) > .css-njf26i")).click()
    await driver.findElement(By.css(".MuiListItem-root:nth-child(1) > .MuiListItemText-root > .MuiTypography-root:nth-child(1)")).click()
    await driver.findElement(By.css(".border-b-2")).click()
    {
      const element = await driver.findElement(By.css(".flex:nth-child(2) #basic-button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".flex:nth-child(3) .h-7")).click()
    await driver.findElement(By.css(".MuiMenuItem-root:nth-child(1)")).click()
  })
})
