// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Leave Group', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Leave Group', async function() {
    await driver.get("http://localhost:3000/chat")
    await driver.manage().window().setRect({ width: 872, height: 693 })
    await driver.findElement(By.css(".px-3")).click()
    await driver.findElement(By.css(".MuiListItem-root:nth-child(1) .MuiTypography-root .MuiTypography-root:nth-child(1)")).click()
    await driver.findElement(By.css(".border-b-2")).click()
    {
      const element = await driver.findElement(By.css(".flex:nth-child(2) #basic-button"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".css-1uxm02a-MuiButtonBase-root-MuiButton-root:nth-child(2)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    {
      const element = await driver.findElement(By.css(".css-1uxm02a-MuiButtonBase-root-MuiButton-root:nth-child(1)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".MuiDialogContent-root > .flex")).click()
    {
      const element = await driver.findElement(By.css(".css-1uxm02a-MuiButtonBase-root-MuiButton-root:nth-child(1)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".css-1uxm02a-MuiButtonBase-root-MuiButton-root:nth-child(1)")).click()
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    await driver.findElement(By.css(".Toastify__close-button > svg")).click()
    await driver.findElement(By.css(".MuiDialog-container")).click()
  })
})
