// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1935, height: 1095 })
    await driver.findElement(By.id("_r_0_")).click()
    await driver.findElement(By.id("_r_0_")).sendKeys("johox93614@discounp.com")
    await driver.findElement(By.id("_r_1_")).sendKeys("vp2036")
    await driver.findElement(By.id("_r_1_")).sendKeys(Key.ENTER)
  })
})
