// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Register', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Register', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1935, height: 1095 })
    await driver.findElement(By.id("_r_4_")).click()
    await driver.findElement(By.id("_r_4_")).sendKeys("Tester")
    await driver.findElement(By.id("_r_5_")).sendKeys("johox93614@discounp.com")
    await driver.findElement(By.id("_r_6_")).sendKeys("vp2036")
    await driver.findElement(By.id("_r_6_")).sendKeys(Key.ENTER)
    {
      const element = await driver.findElement(By.css(".css-1pnbgxn-MuiButtonBase-root-MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".h-12:nth-child(1)")).click()
    await driver.findElement(By.css(".css-1pnbgxn-MuiButtonBase-root-MuiButton-root")).click()
    await driver.findElement(By.css(".h-12:nth-child(1)")).click()
    await driver.findElement(By.css(".h-12:nth-child(1)")).click()
    {
      const element = await driver.findElement(By.css(".h-12:nth-child(1)"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".css-1pnbgxn-MuiButtonBase-root-MuiButton-root")).click()
    {
      const element = await driver.findElement(By.css(".MuiButtonBase-root:nth-child(6)"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
  })
})
