// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Remove Admin', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Remove Admin', async function() {
    await driver.get("http://localhost:3000/chat")
    await driver.manage().window().setRect({ width: 1935, height: 1095 })
    await driver.findElement(By.css(".MuiListItem-root:nth-child(1) > .MuiListItemText-root > .MuiTypography-root:nth-child(1)")).click()
    await driver.findElement(By.css(".border-b-2")).click()
    {
      const element = await driver.findElement(By.css(".css-152a2jk-MuiButtonBase-root-MuiButton-root"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css("div:nth-child(3) > #basic-button > .h-7")).click()
    await driver.findElement(By.css(".MuiMenuItem-root:nth-child(2)")).click()
  })
})
